export type ColorTokens = {
  backgroundCanvas: string;
  backgroundBase: string;
  surfacePanel: string;
  surfaceRaised: string;
  surfaceNeutral: string;
  surfaceNeutralStrong: string;
  surfaceInset: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  actionPrimary: string;
  textOnPrimaryAction: string;
  actionPrimaryHover: string;
  actionPrimaryPressed: string;
  actionSecondary: string;
  actionSecondaryPressed: string;
  accentSignal: string;
  stateSuccess: string;
  stateDanger: string;
  borderAccent: string;
  borderSubtle: string;
  borderFocus: string;
};

export type ThemeDefinition = {
  id: string;
  name: string;
  description: string;
  tokens: ColorTokens;
  builtIn?: boolean;
  updatedAt?: string;
};

export const tokenList: Array<keyof ColorTokens> = [
  "backgroundCanvas",
  "backgroundBase",
  "surfacePanel",
  "surfaceRaised",
  "surfaceNeutral",
  "surfaceNeutralStrong",
  "surfaceInset",
  "textPrimary",
  "textSecondary",
  "textTertiary",
  "actionPrimary",
  "textOnPrimaryAction",
  "actionPrimaryHover",
  "actionPrimaryPressed",
  "actionSecondary",
  "actionSecondaryPressed",
  "accentSignal",
  "stateSuccess",
  "stateDanger",
  "borderAccent",
  "borderSubtle",
  "borderFocus"
];

export const tokenLabels: Record<keyof ColorTokens, string> = {
  backgroundCanvas: "Page background",
  backgroundBase: "App background",
  surfacePanel: "Panel surface",
  surfaceRaised: "Raised surface",
  surfaceNeutral: "Neutral surface",
  surfaceNeutralStrong: "Strong neutral surface",
  surfaceInset: "Inset surface",
  textPrimary: "Primary text",
  textSecondary: "Secondary text",
  textTertiary: "Tertiary text",
  actionPrimary: "Primary action",
  textOnPrimaryAction: "Text on primary action",
  actionPrimaryHover: "Primary action hover",
  actionPrimaryPressed: "Primary action pressed",
  actionSecondary: "Secondary action",
  actionSecondaryPressed: "Secondary action pressed",
  accentSignal: "Signal accent",
  stateSuccess: "Success state",
  stateDanger: "Danger state",
  borderAccent: "Accent border",
  borderSubtle: "Subtle border",
  borderFocus: "Focus border"
};

export const builtInThemes: ThemeDefinition[] = [
  {
    id: "astral",
    name: "Astral",
    description: "A cosmic dark color scheme with bright blue, pink, and orange signal accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#050812",
      backgroundBase: "#0b111b",
      surfacePanel: "#0b111b",
      surfaceRaised: "#101925",
      surfaceNeutral: "#1b2633",
      surfaceNeutralStrong: "#34465b",
      surfaceInset: "#060a10",
      textPrimary: "#f4f7fb",
      textSecondary: "#9aa9ba",
      textTertiary: "#617287",
      actionPrimary: "#ff8a3d",
      textOnPrimaryAction: "#ffb067",
      actionPrimaryHover: "#ffb067",
      actionPrimaryPressed: "#c94d1c",
      actionSecondary: "#27a8ff",
      actionSecondaryPressed: "#0a3e67",
      accentSignal: "#ff5dbb",
      stateSuccess: "#38e6a4",
      stateDanger: "#ff4d5e",
      borderAccent: "#6fc7ff",
      borderSubtle: "#74aedc",
      borderFocus: "#ff8a3d"
    }
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "A dark volcanic glass scheme with restrained metallic sheen instead of punchy accent color.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#06070a",
      backgroundBase: "#0b0d10",
      surfacePanel: "#101318",
      surfaceRaised: "#171b22",
      surfaceNeutral: "#242a33",
      surfaceNeutralStrong: "#6f7885",
      surfaceInset: "#030406",
      textPrimary: "#e5e7eb",
      textSecondary: "#a7adb7",
      textTertiary: "#6f7885",
      actionPrimary: "#8b949e",
      textOnPrimaryAction: "#f2f4f8",
      actionPrimaryHover: "#c9d1d9",
      actionPrimaryPressed: "#4b5563",
      actionSecondary: "#717784",
      actionSecondaryPressed: "#30363d",
      accentSignal: "#b8c0cc",
      stateSuccess: "#8fa99a",
      stateDanger: "#b28a8a",
      borderAccent: "#c9d1d9",
      borderSubtle: "#4b5563",
      borderFocus: "#d1d5db"
    }
  },
  {
    id: "ember",
    name: "Ember",
    description: "A fire-lit color scheme for decisive actions, alerts, crafting, and forge-like tooling.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#140908",
      backgroundBase: "#26110d",
      surfacePanel: "#26110d",
      surfaceRaised: "#35170f",
      surfaceNeutral: "#4a2518",
      surfaceNeutralStrong: "#7c3a24",
      surfaceInset: "#0f0806",
      textPrimary: "#feece2",
      textSecondary: "#d9a894",
      textTertiary: "#9f6b57",
      actionPrimary: "#fb923c",
      textOnPrimaryAction: "#fdba74",
      actionPrimaryHover: "#fdba74",
      actionPrimaryPressed: "#c2410c",
      actionSecondary: "#facc15",
      actionSecondaryPressed: "#713f12",
      accentSignal: "#fb7185",
      stateSuccess: "#86efac",
      stateDanger: "#f43f5e",
      borderAccent: "#f97316",
      borderSubtle: "#fbbf24",
      borderFocus: "#fb923c"
    }
  },
  {
    id: "tidal",
    name: "Tidal",
    description: "An oceanic blue color scheme with deep water surfaces, cyan currents, and cool navigation accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#06111f",
      backgroundBase: "#0f1d2e",
      surfacePanel: "#0f1d2e",
      surfaceRaised: "#13283f",
      surfaceNeutral: "#1f3b57",
      surfaceNeutralStrong: "#35607d",
      surfaceInset: "#04101c",
      textPrimary: "#e0f2fe",
      textSecondary: "#93c5fd",
      textTertiary: "#5f87ad",
      actionPrimary: "#38bdf8",
      textOnPrimaryAction: "#e0f2fe",
      actionPrimaryHover: "#7dd3fc",
      actionPrimaryPressed: "#0369a1",
      actionSecondary: "#22d3ee",
      actionSecondaryPressed: "#155e75",
      accentSignal: "#a78bfa",
      stateSuccess: "#34d399",
      stateDanger: "#fb7185",
      borderAccent: "#67e8f9",
      borderSubtle: "#67e8f9",
      borderFocus: "#38bdf8"
    }
  },
  {
    id: "frost",
    name: "Frost",
    description: "A freezing color scheme with pale blue highlights, icy greys, and frostbitten surfaces.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#101820",
      backgroundBase: "#17212b",
      surfacePanel: "#202b36",
      surfaceRaised: "#2b3845",
      surfaceNeutral: "#3d4b59",
      surfaceNeutralStrong: "#708191",
      surfaceInset: "#0b1117",
      textPrimary: "#edf7ff",
      textSecondary: "#c2d3df",
      textTertiary: "#8fa2b0",
      actionPrimary: "#b8e6ff",
      textOnPrimaryAction: "#10202d",
      actionPrimaryHover: "#d8f3ff",
      actionPrimaryPressed: "#78b9d6",
      actionSecondary: "#9cc7d8",
      actionSecondaryPressed: "#5d8799",
      accentSignal: "#d7e6ef",
      stateSuccess: "#9fd6c2",
      stateDanger: "#d69aa6",
      borderAccent: "#c9edff",
      borderSubtle: "#6f8493",
      borderFocus: "#e5f7ff"
    }
  },
  {
    id: "verdant",
    name: "Verdant",
    description: "A living green color scheme for knowledge growth, gardens, recipes, notes, and renewal.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#07130d",
      backgroundBase: "#102016",
      surfacePanel: "#102016",
      surfaceRaised: "#152c1d",
      surfaceNeutral: "#1f3a2a",
      surfaceNeutralStrong: "#356548",
      surfaceInset: "#041109",
      textPrimary: "#dcfce7",
      textSecondary: "#a7d7b7",
      textTertiary: "#6b9678",
      actionPrimary: "#22c55e",
      textOnPrimaryAction: "#dcfce7",
      actionPrimaryHover: "#86efac",
      actionPrimaryPressed: "#15803d",
      actionSecondary: "#5eead4",
      actionSecondaryPressed: "#0f766e",
      accentSignal: "#f472b6",
      stateSuccess: "#4ade80",
      stateDanger: "#fb7185",
      borderAccent: "#86efac",
      borderSubtle: "#5eead4",
      borderFocus: "#22c55e"
    }
  },
  {
    id: "heavenly",
    name: "Heavenly",
    description: "A light pearl-sky color scheme with luminous panels, celestial blues, and warm gold action states.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#f7fbff",
      backgroundBase: "#edf6ff",
      surfacePanel: "#ffffff",
      surfaceRaised: "#f0f7ff",
      surfaceNeutral: "#d7e7f7",
      surfaceNeutralStrong: "#aac6df",
      surfaceInset: "#e4f0fb",
      textPrimary: "#142235",
      textSecondary: "#4f6680",
      textTertiary: "#7b91aa",
      actionPrimary: "#f59e0b",
      textOnPrimaryAction: "#8bcdea",
      actionPrimaryHover: "#fbbf24",
      actionPrimaryPressed: "#b45309",
      actionSecondary: "#0ea5e9",
      actionSecondaryPressed: "#0369a1",
      accentSignal: "#d946ef",
      stateSuccess: "#059669",
      stateDanger: "#e11d48",
      borderAccent: "#38bdf8",
      borderSubtle: "#93c5fd",
      borderFocus: "#f59e0b"
    }
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    description: "Catppuccin's light palette: soft cream surfaces, calm blue actions, and pastel status colors.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#eff1f5",
      backgroundBase: "#e6e9ef",
      surfacePanel: "#ffffff",
      surfaceRaised: "#ccd0da",
      surfaceNeutral: "#bcc0cc",
      surfaceNeutralStrong: "#acb0be",
      surfaceInset: "#dce0e8",
      textPrimary: "#4c4f69",
      textSecondary: "#5c5f77",
      textTertiary: "#6c6f85",
      actionPrimary: "#1e66f5",
      textOnPrimaryAction: "#eff1f5",
      actionPrimaryHover: "#7287fd",
      actionPrimaryPressed: "#1e3a8a",
      actionSecondary: "#04a5e5",
      actionSecondaryPressed: "#0a7896",
      accentSignal: "#ea76cb",
      stateSuccess: "#40a02b",
      stateDanger: "#d20f39",
      borderAccent: "#209fb5",
      borderSubtle: "#acb0be",
      borderFocus: "#fe640b"
    }
  },
  {
    id: "catppuccin-frappe",
    name: "Catppuccin Frappé",
    description: "Catppuccin's dusky medium-dark palette with blue actions and lavender-pink accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#232634",
      backgroundBase: "#292c3c",
      surfacePanel: "#303446",
      surfaceRaised: "#414559",
      surfaceNeutral: "#51576d",
      surfaceNeutralStrong: "#626880",
      surfaceInset: "#232634",
      textPrimary: "#c6d0f5",
      textSecondary: "#b5bfe2",
      textTertiary: "#a5adce",
      actionPrimary: "#8caaee",
      textOnPrimaryAction: "#232634",
      actionPrimaryHover: "#babbf1",
      actionPrimaryPressed: "#5b77b8",
      actionSecondary: "#99d1db",
      actionSecondaryPressed: "#5f9daa",
      accentSignal: "#f4b8e4",
      stateSuccess: "#a6d189",
      stateDanger: "#e78284",
      borderAccent: "#99d1db",
      borderSubtle: "#626880",
      borderFocus: "#ef9f76"
    }
  },
  {
    id: "catppuccin-macchiato",
    name: "Catppuccin Macchiato",
    description: "Catppuccin's deeper blue-gray palette with soft blue actions and rose signal accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#181926",
      backgroundBase: "#1e2030",
      surfacePanel: "#24273a",
      surfaceRaised: "#363a4f",
      surfaceNeutral: "#494d64",
      surfaceNeutralStrong: "#5b6078",
      surfaceInset: "#181926",
      textPrimary: "#cad3f5",
      textSecondary: "#b8c0e0",
      textTertiary: "#a5adcb",
      actionPrimary: "#8aadf4",
      textOnPrimaryAction: "#181926",
      actionPrimaryHover: "#b7bdf8",
      actionPrimaryPressed: "#5f7fbd",
      actionSecondary: "#91d7e3",
      actionSecondaryPressed: "#5aa6b6",
      accentSignal: "#f5bde6",
      stateSuccess: "#a6da95",
      stateDanger: "#ed8796",
      borderAccent: "#91d7e3",
      borderSubtle: "#5b6078",
      borderFocus: "#f5a97f"
    }
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    description: "Catppuccin's darkest palette: rich midnight surfaces, blue actions, and candy-toned accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#11111b",
      backgroundBase: "#181825",
      surfacePanel: "#1e1e2e",
      surfaceRaised: "#313244",
      surfaceNeutral: "#45475a",
      surfaceNeutralStrong: "#585b70",
      surfaceInset: "#11111b",
      textPrimary: "#cdd6f4",
      textSecondary: "#bac2de",
      textTertiary: "#a6adc8",
      actionPrimary: "#89b4fa",
      textOnPrimaryAction: "#11111b",
      actionPrimaryHover: "#b4befe",
      actionPrimaryPressed: "#5b7fbf",
      actionSecondary: "#89dceb",
      actionSecondaryPressed: "#4d9ead",
      accentSignal: "#f5c2e7",
      stateSuccess: "#a6e3a1",
      stateDanger: "#f38ba8",
      borderAccent: "#89dceb",
      borderSubtle: "#585b70",
      borderFocus: "#fab387"
    }
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "The classic high-contrast dark palette with purple surfaces, cyan actions, and pink signals.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#282a36",
      backgroundBase: "#282a36",
      surfacePanel: "#343746",
      surfaceRaised: "#44475a",
      surfaceNeutral: "#44475a",
      surfaceNeutralStrong: "#6272a4",
      surfaceInset: "#1f2029",
      textPrimary: "#f8f8f2",
      textSecondary: "#c8c8c2",
      textTertiary: "#6272a4",
      actionPrimary: "#bd93f9",
      textOnPrimaryAction: "#282a36",
      actionPrimaryHover: "#ff79c6",
      actionPrimaryPressed: "#7b56b8",
      actionSecondary: "#8be9fd",
      actionSecondaryPressed: "#2aa7b8",
      accentSignal: "#ff79c6",
      stateSuccess: "#50fa7b",
      stateDanger: "#ff5555",
      borderAccent: "#8be9fd",
      borderSubtle: "#6272a4",
      borderFocus: "#ffb86c"
    }
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Tokyo Night's original deep terminal palette with saturated blue actions and magenta accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#16161e",
      backgroundBase: "#1a1b26",
      surfacePanel: "#1f2335",
      surfaceRaised: "#292e42",
      surfaceNeutral: "#414868",
      surfaceNeutralStrong: "#565f89",
      surfaceInset: "#16161e",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      textTertiary: "#565f89",
      actionPrimary: "#7aa2f7",
      textOnPrimaryAction: "#16161e",
      actionPrimaryHover: "#bb9af7",
      actionPrimaryPressed: "#3d59a1",
      actionSecondary: "#7dcfff",
      actionSecondaryPressed: "#2e87b7",
      accentSignal: "#bb9af7",
      stateSuccess: "#9ece6a",
      stateDanger: "#f7768e",
      borderAccent: "#7dcfff",
      borderSubtle: "#565f89",
      borderFocus: "#e0af68"
    }
  },
  {
    id: "tokyo-night-storm",
    name: "Tokyo Night Storm",
    description: "A slightly brighter Tokyo Night variant with storm-blue panels and clear blue actions.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#1f2335",
      backgroundBase: "#24283b",
      surfacePanel: "#292e42",
      surfaceRaised: "#3b4261",
      surfaceNeutral: "#414868",
      surfaceNeutralStrong: "#565f89",
      surfaceInset: "#1f2335",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      textTertiary: "#737aa2",
      actionPrimary: "#7aa2f7",
      textOnPrimaryAction: "#1f2335",
      actionPrimaryHover: "#bb9af7",
      actionPrimaryPressed: "#3d59a1",
      actionSecondary: "#7dcfff",
      actionSecondaryPressed: "#2e87b7",
      accentSignal: "#bb9af7",
      stateSuccess: "#9ece6a",
      stateDanger: "#f7768e",
      borderAccent: "#7dcfff",
      borderSubtle: "#565f89",
      borderFocus: "#e0af68"
    }
  },
  {
    id: "tokyo-night-moon",
    name: "Tokyo Night Moon",
    description: "Tokyo Night's moonlit variant with cooler blues, lilac accents, and soft green status states.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#1e2030",
      backgroundBase: "#222436",
      surfacePanel: "#2f334d",
      surfaceRaised: "#444a73",
      surfaceNeutral: "#444a73",
      surfaceNeutralStrong: "#636da6",
      surfaceInset: "#1b1d2b",
      textPrimary: "#c8d3f5",
      textSecondary: "#b4c2f0",
      textTertiary: "#828bb8",
      actionPrimary: "#82aaff",
      textOnPrimaryAction: "#1e2030",
      actionPrimaryHover: "#c099ff",
      actionPrimaryPressed: "#4f6fb5",
      actionSecondary: "#86e1fc",
      actionSecondaryPressed: "#4aa6bf",
      accentSignal: "#c099ff",
      stateSuccess: "#c3e88d",
      stateDanger: "#ff757f",
      borderAccent: "#86e1fc",
      borderSubtle: "#636da6",
      borderFocus: "#ffc777"
    }
  },
  {
    id: "tokyo-night-day",
    name: "Tokyo Night Day",
    description: "Tokyo Night's light variant with quiet blue-gray surfaces and strong blue actions.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#e1e2e7",
      backgroundBase: "#d5d6db",
      surfacePanel: "#ffffff",
      surfaceRaised: "#c4c8da",
      surfaceNeutral: "#a8aecb",
      surfaceNeutralStrong: "#848cb5",
      surfaceInset: "#cfd2df",
      textPrimary: "#3760bf",
      textSecondary: "#6172b0",
      textTertiary: "#848cb5",
      actionPrimary: "#2e7de9",
      textOnPrimaryAction: "#ffffff",
      actionPrimaryHover: "#9854f1",
      actionPrimaryPressed: "#1f4f99",
      actionSecondary: "#007197",
      actionSecondaryPressed: "#004f69",
      accentSignal: "#9854f1",
      stateSuccess: "#587539",
      stateDanger: "#f52a65",
      borderAccent: "#007197",
      borderSubtle: "#848cb5",
      borderFocus: "#8c6c3e"
    }
  },
  {
    id: "nord",
    name: "Nord",
    description: "Arctic blue-gray surfaces with frosty blue actions and calm aurora status colors.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#2e3440",
      backgroundBase: "#3b4252",
      surfacePanel: "#3b4252",
      surfaceRaised: "#434c5e",
      surfaceNeutral: "#4c566a",
      surfaceNeutralStrong: "#5e81ac",
      surfaceInset: "#242933",
      textPrimary: "#eceff4",
      textSecondary: "#d8dee9",
      textTertiary: "#aab3c0",
      actionPrimary: "#88c0d0",
      textOnPrimaryAction: "#2e3440",
      actionPrimaryHover: "#8fbcbb",
      actionPrimaryPressed: "#5e81ac",
      actionSecondary: "#81a1c1",
      actionSecondaryPressed: "#4f6b8f",
      accentSignal: "#b48ead",
      stateSuccess: "#a3be8c",
      stateDanger: "#bf616a",
      borderAccent: "#88c0d0",
      borderSubtle: "#4c566a",
      borderFocus: "#ebcb8b"
    }
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    description: "Ethan Schoonover's low-contrast dark palette with balanced blue actions and warm focus states.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#002b36",
      backgroundBase: "#073642",
      surfacePanel: "#073642",
      surfaceRaised: "#0b3f4c",
      surfaceNeutral: "#586e75",
      surfaceNeutralStrong: "#657b83",
      surfaceInset: "#001f27",
      textPrimary: "#839496",
      textSecondary: "#93a1a1",
      textTertiary: "#657b83",
      actionPrimary: "#268bd2",
      textOnPrimaryAction: "#002b36",
      actionPrimaryHover: "#6c71c4",
      actionPrimaryPressed: "#1d668f",
      actionSecondary: "#2aa198",
      actionSecondaryPressed: "#1d6f69",
      accentSignal: "#d33682",
      stateSuccess: "#859900",
      stateDanger: "#dc322f",
      borderAccent: "#2aa198",
      borderSubtle: "#586e75",
      borderFocus: "#b58900"
    }
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    description: "Solarized's light palette with cream pages, muted ink, and precise blue actions.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#fdf6e3",
      backgroundBase: "#eee8d5",
      surfacePanel: "#fffbea",
      surfaceRaised: "#e5dec8",
      surfaceNeutral: "#93a1a1",
      surfaceNeutralStrong: "#839496",
      surfaceInset: "#eee8d5",
      textPrimary: "#657b83",
      textSecondary: "#586e75",
      textTertiary: "#839496",
      actionPrimary: "#268bd2",
      textOnPrimaryAction: "#fdf6e3",
      actionPrimaryHover: "#6c71c4",
      actionPrimaryPressed: "#1d668f",
      actionSecondary: "#2aa198",
      actionSecondaryPressed: "#1d6f69",
      accentSignal: "#d33682",
      stateSuccess: "#859900",
      stateDanger: "#dc322f",
      borderAccent: "#2aa198",
      borderSubtle: "#93a1a1",
      borderFocus: "#b58900"
    }
  },
  {
    id: "gruvbox-dark-hard",
    name: "Gruvbox Dark Hard",
    description: "Gruvbox's highest-contrast dark variant with earthy yellow actions and retro terminal warmth.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#1d2021",
      backgroundBase: "#282828",
      surfacePanel: "#282828",
      surfaceRaised: "#3c3836",
      surfaceNeutral: "#504945",
      surfaceNeutralStrong: "#665c54",
      surfaceInset: "#1d2021",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textTertiary: "#928374",
      actionPrimary: "#d79921",
      textOnPrimaryAction: "#1d2021",
      actionPrimaryHover: "#fabd2f",
      actionPrimaryPressed: "#b57614",
      actionSecondary: "#458588",
      actionSecondaryPressed: "#076678",
      accentSignal: "#b16286",
      stateSuccess: "#98971a",
      stateDanger: "#cc241d",
      borderAccent: "#83a598",
      borderSubtle: "#665c54",
      borderFocus: "#d65d0e"
    }
  },
  {
    id: "gruvbox-dark-medium",
    name: "Gruvbox Dark Medium",
    description: "Gruvbox's balanced dark variant with warm surfaces and vintage terminal contrast.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#282828",
      backgroundBase: "#32302f",
      surfacePanel: "#3c3836",
      surfaceRaised: "#504945",
      surfaceNeutral: "#665c54",
      surfaceNeutralStrong: "#7c6f64",
      surfaceInset: "#1d2021",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textTertiary: "#928374",
      actionPrimary: "#d79921",
      textOnPrimaryAction: "#282828",
      actionPrimaryHover: "#fabd2f",
      actionPrimaryPressed: "#b57614",
      actionSecondary: "#458588",
      actionSecondaryPressed: "#076678",
      accentSignal: "#b16286",
      stateSuccess: "#98971a",
      stateDanger: "#cc241d",
      borderAccent: "#83a598",
      borderSubtle: "#665c54",
      borderFocus: "#d65d0e"
    }
  },
  {
    id: "gruvbox-dark-soft",
    name: "Gruvbox Dark Soft",
    description: "Gruvbox's softer dark variant with gentler brown surfaces and warm yellow actions.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#32302f",
      backgroundBase: "#3c3836",
      surfacePanel: "#3c3836",
      surfaceRaised: "#504945",
      surfaceNeutral: "#665c54",
      surfaceNeutralStrong: "#7c6f64",
      surfaceInset: "#282828",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textTertiary: "#928374",
      actionPrimary: "#d79921",
      textOnPrimaryAction: "#282828",
      actionPrimaryHover: "#fabd2f",
      actionPrimaryPressed: "#b57614",
      actionSecondary: "#458588",
      actionSecondaryPressed: "#076678",
      accentSignal: "#b16286",
      stateSuccess: "#98971a",
      stateDanger: "#cc241d",
      borderAccent: "#83a598",
      borderSubtle: "#7c6f64",
      borderFocus: "#d65d0e"
    }
  },
  {
    id: "gruvbox-light-hard",
    name: "Gruvbox Light Hard",
    description: "Gruvbox's crisp light variant with cream surfaces, dark ink, and earthy action colors.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#f9f5d7",
      backgroundBase: "#fbf1c7",
      surfacePanel: "#fff7d6",
      surfaceRaised: "#ebdbb2",
      surfaceNeutral: "#d5c4a1",
      surfaceNeutralStrong: "#bdae93",
      surfaceInset: "#f2e5bc",
      textPrimary: "#3c3836",
      textSecondary: "#504945",
      textTertiary: "#7c6f64",
      actionPrimary: "#b57614",
      textOnPrimaryAction: "#fbf1c7",
      actionPrimaryHover: "#d79921",
      actionPrimaryPressed: "#8f3f0a",
      actionSecondary: "#076678",
      actionSecondaryPressed: "#07545f",
      accentSignal: "#8f3f71",
      stateSuccess: "#79740e",
      stateDanger: "#9d0006",
      borderAccent: "#458588",
      borderSubtle: "#bdae93",
      borderFocus: "#af3a03"
    }
  },
  {
    id: "gruvbox-light-medium",
    name: "Gruvbox Light Medium",
    description: "Gruvbox's default light variant with aged-paper surfaces and classic terminal colors.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#fbf1c7",
      backgroundBase: "#f2e5bc",
      surfacePanel: "#fff7d6",
      surfaceRaised: "#ebdbb2",
      surfaceNeutral: "#d5c4a1",
      surfaceNeutralStrong: "#bdae93",
      surfaceInset: "#ebdbb2",
      textPrimary: "#3c3836",
      textSecondary: "#504945",
      textTertiary: "#7c6f64",
      actionPrimary: "#b57614",
      textOnPrimaryAction: "#fbf1c7",
      actionPrimaryHover: "#d79921",
      actionPrimaryPressed: "#8f3f0a",
      actionSecondary: "#076678",
      actionSecondaryPressed: "#07545f",
      accentSignal: "#8f3f71",
      stateSuccess: "#79740e",
      stateDanger: "#9d0006",
      borderAccent: "#458588",
      borderSubtle: "#bdae93",
      borderFocus: "#af3a03"
    }
  },
  {
    id: "gruvbox-light-soft",
    name: "Gruvbox Light Soft",
    description: "Gruvbox's softest light variant with warmer paper surfaces and muted contrast.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#f2e5bc",
      backgroundBase: "#ebdbb2",
      surfacePanel: "#fbf1c7",
      surfaceRaised: "#d5c4a1",
      surfaceNeutral: "#bdae93",
      surfaceNeutralStrong: "#a89984",
      surfaceInset: "#ead8a8",
      textPrimary: "#3c3836",
      textSecondary: "#504945",
      textTertiary: "#7c6f64",
      actionPrimary: "#b57614",
      textOnPrimaryAction: "#fbf1c7",
      actionPrimaryHover: "#d79921",
      actionPrimaryPressed: "#8f3f0a",
      actionSecondary: "#076678",
      actionSecondaryPressed: "#07545f",
      accentSignal: "#8f3f71",
      stateSuccess: "#79740e",
      stateDanger: "#9d0006",
      borderAccent: "#458588",
      borderSubtle: "#a89984",
      borderFocus: "#af3a03"
    }
  },
  {
    id: "iceberg-dark",
    name: "Iceberg Dark",
    description: "A cool, quiet dark palette with blue-gray surfaces, glacial actions, and restrained accents.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#161821",
      backgroundBase: "#1e2132",
      surfacePanel: "#242940",
      surfaceRaised: "#2e344f",
      surfaceNeutral: "#3e445e",
      surfaceNeutralStrong: "#6b7089",
      surfaceInset: "#11131a",
      textPrimary: "#c6c8d1",
      textSecondary: "#a7adba",
      textTertiary: "#6b7089",
      actionPrimary: "#84a0c6",
      textOnPrimaryAction: "#161821",
      actionPrimaryHover: "#a093c7",
      actionPrimaryPressed: "#52719b",
      actionSecondary: "#89b8c2",
      actionSecondaryPressed: "#4f8994",
      accentSignal: "#a093c7",
      stateSuccess: "#b4be82",
      stateDanger: "#e27878",
      borderAccent: "#89b8c2",
      borderSubtle: "#6b7089",
      borderFocus: "#e2a478"
    }
  },
  {
    id: "iceberg-light",
    name: "Iceberg Light",
    description: "Iceberg's light palette with cool paper surfaces, blue actions, and restrained editorial contrast.",
    builtIn: true,
    tokens: {
      backgroundCanvas: "#e8e9ec",
      backgroundBase: "#dcdfe7",
      surfacePanel: "#f3f4f7",
      surfaceRaised: "#cdd1dc",
      surfaceNeutral: "#b8bfd0",
      surfaceNeutralStrong: "#8389a3",
      surfaceInset: "#d8dce6",
      textPrimary: "#33374c",
      textSecondary: "#555b76",
      textTertiary: "#8389a3",
      actionPrimary: "#2d539e",
      textOnPrimaryAction: "#f3f4f7",
      actionPrimaryHover: "#7759b4",
      actionPrimaryPressed: "#1d3b75",
      actionSecondary: "#327698",
      actionSecondaryPressed: "#25566f",
      accentSignal: "#7759b4",
      stateSuccess: "#668e3d",
      stateDanger: "#cc517a",
      borderAccent: "#327698",
      borderSubtle: "#8389a3",
      borderFocus: "#c57339"
    }
  }
];

export const defaultPalettes: Record<string, ColorTokens> = Object.fromEntries(
  builtInThemes.map((theme) => [theme.name, theme.tokens])
);

export function cloneTokens(tokens: ColorTokens): ColorTokens {
  return { ...tokens };
}
